// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQWydCUAVMidUGdj3PB7of2EpUXf-Cts',
    appId: '1:167574698591:web:e257291aba0485de53b9ea',
    messagingSenderId: '167574698591',
    projectId: 'shixin-18e28',
    authDomain: 'shixin-18e28.firebaseapp.com',
    storageBucket: 'shixin-18e28.firebasestorage.app',
    measurementId: 'G-WW5TX046QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWhv_Wwc93FSYJ1XpDyjJ7baROFF1D-Q',
    appId: '1:167574698591:android:83deaaf95b7f3e5d53b9ea',
    messagingSenderId: '167574698591',
    projectId: 'shixin-18e28',
    storageBucket: 'shixin-18e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2cuMdk0dvVg8Phhbz9xa1ksKCUJb8sg',
    appId: '1:167574698591:ios:60016ed4c50d78c453b9ea',
    messagingSenderId: '167574698591',
    projectId: 'shixin-18e28',
    storageBucket: 'shixin-18e28.firebasestorage.app',
    iosBundleId: 'com.shixincrmor.litechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2cuMdk0dvVg8Phhbz9xa1ksKCUJb8sg',
    appId: '1:167574698591:ios:60016ed4c50d78c453b9ea',
    messagingSenderId: '167574698591',
    projectId: 'shixin-18e28',
    storageBucket: 'shixin-18e28.firebasestorage.app',
    iosBundleId: 'com.shixincrmor.litechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQWydCUAVMidUGdj3PB7of2EpUXf-Cts',
    appId: '1:167574698591:web:f6cc86bb713d8d3253b9ea',
    messagingSenderId: '167574698591',
    projectId: 'shixin-18e28',
    authDomain: 'shixin-18e28.firebaseapp.com',
    storageBucket: 'shixin-18e28.firebasestorage.app',
    measurementId: 'G-49TV54XHTX',
  );
}
