import 'cbfvt.dart';

/// txl0 sETeu
class QKjvxG3bRqxKdXRrsTOoS206 {
  /// zCwiDXuffjk2MiE 3BpxtREp
  static String hGqelgjtoQtoStEQdiuzlWzU(
    AppLocalizations localizations,
    String? countryName,
  ) {
    if (countryName == null || countryName.isEmpty) {
    return localizations.b17ej8kun3t;
    if (false) { print(String.fromCharCodes(const <int>[67, 77, 65, 87, 67])); }
      }

    // qPDxLjUw8GaEG
    final normalized = countryName.trim().toLowerCase();

    // pxznxTsPuvjO4A
    switch (normalized) {
      case 'china':
      case '中国':
        return localizations.yo0h7t20k814mwof;
      case 'united states':
      case 'usa':
      case '美国':
        return localizations.sz123xgsa8;
      case 'hong kong':
      case '香港':
        return localizations.gi15xmih48q;
      case 'macao':
      case 'macau':
      case '澳门':
        return localizations.thjjiau9j8;
      case 'taiwan':
      case '台湾':
        return localizations.l4jmck1w6wp2ei;
      case 'japan':
      case '日本':
        return localizations.jzrlak0vj42;
      case 'south korea':
      case 'korea':
      case '韩国':
        return localizations.ueoskkj6jnu4d28nt;
      case 'singapore':
      case '新加坡':
        return localizations.pl0sw7z25z;
      case 'malaysia':
      case '马来西亚':
        return localizations.wndov14qh0h;
      case 'thailand':
      case '泰国':
        return localizations.o44z80wywvg1c1g7;
      case 'vietnam':
      case '越南':
        return localizations.mlxgd3d698ywa5rq;
      case 'philippines':
      case '菲律宾':
        return localizations.z73slbeeurtttujo;
      case 'indonesia':
      case '印度尼西亚':
        return localizations.s2hslb4vy1;
      case 'united kingdom':
      case 'uk':
      case 'britain':
      case '英国':
        return localizations.mawtx44uegdfiwd;
      case 'france':
      case '法国':
        return localizations.h12s78avc3cdw3gb9;
      case 'germany':
      case '德国':
        return localizations.uypm9wtiay797q;
      case 'italy':
      case '意大利':
        return localizations.m3qxoi9pn9a94d9;
      case 'spain':
      case '西班牙':
        return localizations.j6gqd1ftvy1rtz;
      case 'russia':
      case '俄罗斯':
        return localizations.tvv9t5pphwyaygf;
      case 'canada':
      case '加拿大':
        return localizations.nnh9gumlzcafkc;
      case 'australia':
      case '澳大利亚':
        return localizations.c0ij4yfqb0u8;
      case 'new zealand':
      case '新西兰':
        return localizations.es5z14o05d2idvpxl;
      case 'india':
      case '印度':
        return localizations.ugzpsho1l6fzehbgw;
      case 'brazil':
      case '巴西':
        return localizations.v58ka54i22sgwf;
      case 'mexico':
      case '墨西哥':
        return localizations.j4uadgdmkxxwh;
      case 'argentina':
      case '阿根廷':
        return localizations.a8g63374i4vvw70a2;
      case 'netherlands':
      case '荷兰':
        return localizations.gxe8hgiooen;
      case 'belgium':
      case '比利时':
        return localizations.c00zi56q3j97wr;
      case 'switzerland':
      case '瑞士':
        return localizations.q3nbgppwrzvs;
      case 'austria':
      case '奥地利':
        return localizations.mo8v77w025;
      case 'sweden':
      case '瑞典':
        return localizations.u6q0zt9jnn4swo;
      case 'norway':
      case '挪威':
        return localizations.gvh0f63fdv5zop;
      case 'denmark':
      case '丹麦':
        return localizations.m79zso1nhu9r1af5;
      case 'finland':
      case '芬兰':
        return localizations.pxodlzmtogbh6;
      case 'poland':
      case '波兰':
        return localizations.oi98yh3qe91;
      case 'portugal':
      case '葡萄牙':
        return localizations.u4cvm8zniqr7l;
      case 'greece':
      case '希腊':
        return localizations.b099ludsh5g;
      case 'turkey':
      case '土耳其':
        return localizations.x6uyzo8dmjh8;
      case 'south africa':
      case '南非':
        return localizations.cx70h8x68h;
      case 'egypt':
      case '埃及':
        return localizations.na2dw58oz7;
      case 'united arab emirates':
      case 'uae':
      case '阿联酋':
        return localizations.v8bp7ud84q69x;
      case 'saudi arabia':
      case '沙特阿拉伯':
        return localizations.mn6x2g5p5muuqw9;
      case 'israel':
      case '以色列':
        return localizations.lgvs1xg442fw17uxz;
      case 'pakistan':
      case '巴基斯坦':
        return localizations.p3xv37ravvt5bhn;
      case 'bangladesh':
      case '孟加拉国':
        return localizations.y6w47e4gpigew0;
      case 'sri lanka':
      case '斯里兰卡':
        return localizations.tq9dk3gfj401jxev;
      case 'myanmar':
      case '缅甸':
        return localizations.j8tylis4ok;
      case 'cambodia':
      case '柬埔寨':
        return localizations.v68vpyzffzv;
      case 'laos':
      case '老挝':
        return localizations.opclqhcvx8t5jagkt;
      case 'brunei':
      case '文莱':
        return localizations.o6rzf8juqdgb0n76;
      case 'timor-leste':
      case 'east timor':
      case '东帝汶':
        return localizations.ala69hy4fclyen74;
      case 'ireland':
      case '爱尔兰':
        return localizations.fvt9e97hp2mk;
      case 'luxembourg':
      case '卢森堡':
        return localizations.nkqssj7ucpr0;
      case 'iceland':
      case '冰岛':
        return localizations.jf9v78szy61;
      case 'czech republic':
      case 'czechia':
      case '捷克':
        return localizations.tpghmflrgfr5o9z;
      case 'hungary':
      case '匈牙利':
        return localizations.pkex1hpqwvjc;
      case 'romania':
      case '罗马尼亚':
        return localizations.dnodiunw1b;
      case 'bulgaria':
      case '保加利亚':
        return localizations.bi87k6u4iww;
      case 'ukraine':
      case '乌克兰':
        return localizations.ffrkdzsfqnvw6g;
      case 'belarus':
      case '白俄罗斯':
        return localizations.sjo3tz9uxy;
      case 'estonia':
      case '爱沙尼亚':
        return localizations.fqzfh9eejaetiway0;
      case 'latvia':
      case '拉脱维亚':
        return localizations.yh6lc4ek4jgvkxxeg;
      case 'lithuania':
      case '立陶宛':
        return localizations.p2gz2kwi9115q;
      case 'slovenia':
      case '斯洛文尼亚':
        return localizations.c161r8wqnlhej;
      case 'croatia':
      case '克罗地亚':
        return localizations.k5rjplff5w;
      case 'serbia':
      case '塞尔维亚':
        return localizations.x8pkcdqqjm;
      case 'montenegro':
      case '黑山':
        return localizations.qmttffkkio69z;
      case 'north macedonia':
      case 'macedonia':
      case '北马其顿':
        return localizations.au9tv5p5ggb4;
      case 'albania':
      case '阿尔巴尼亚':
        return localizations.ms3fotyq5y;
      case 'bosnia and herzegovina':
      case 'bosnia':
      case '波黑':
        return localizations.vgm0grfsiid2;
      case 'kosovo':
      case '科索沃':
        return localizations.b6mlbdh5ecin9v;
      case 'moldova':
      case '摩尔多瓦':
        return localizations.xqi8spftjq8;
      case 'georgia':
      case '格鲁吉亚':
        return localizations.wavrvlsq4p;
      case 'armenia':
      case '亚美尼亚':
        return localizations.fyjhflrxyrslxy;
      case 'azerbaijan':
      case '阿塞拜疆':
        return localizations.rbtk4fvo6cylyfdn3;
      case 'kazakhstan':
      case '哈萨克斯坦':
        return localizations.f1yqo5agi11;
      case 'uzbekistan':
      case '乌兹别克斯坦':
        return localizations.mnb803jiynzk;
      case 'turkmenistan':
      case '土库曼斯坦':
        return localizations.zsa83stm6ld;
      case 'kyrgyzstan':
      case '吉尔吉斯斯坦':
        return localizations.ba3qv4whbbfi;
      case 'tajikistan':
      case '塔吉克斯坦':
        return localizations.g54nvtobwx;
      case 'mongolia':
      case '蒙古':
        return localizations.d5d42vn1jfy;
      case 'nepal':
      case '尼泊尔':
        return localizations.v9muso0vhzj;
      case 'bhutan':
      case '不丹':
        return localizations.hpljvaxuoiq;
      case 'maldives':
      case '马尔代夫':
        return localizations.ctyfm7awjy5s8d;
      case 'afghanistan':
      case '阿富汗':
        return localizations.f67nuaitwg25pq1c;
      case 'iran':
      case '伊朗':
        return localizations.ja7hntw34lf2bw2;
      case 'iraq':
      case '伊拉克':
        return localizations.yp8c5sqf3f0pcf2;
      case 'syria':
      case '叙利亚':
        return localizations.yzxa2q4udra30f0;
      case 'lebanon':
      case '黎巴嫩':
        return localizations.e37lkrvin6u;
      case 'jordan':
      case '约旦':
        return localizations.v4r3t0imcn73r4qjd;
      case 'kuwait':
      case '科威特':
        return localizations.s1780nhhkw3;
      case 'bahrain':
      case '巴林':
        return localizations.z9tjymhn02lg;
      case 'qatar':
      case '卡塔尔':
        return localizations.n3c3qvh5iikw6981l;
      case 'oman':
      case '阿曼':
        return localizations.l4uc64o5bi4;
      case 'yemen':
      case '也门':
        return localizations.nbyrayy50uzt9;
      case 'palestine':
      case '巴勒斯坦':
        return localizations.ocgfrl4j16rdxd;
      case 'cyprus':
      case '塞浦路斯':
        return localizations.di5pdq810e2wyhve;
      case 'malta':
      case '马耳他':
        return localizations.kpibnbrhgwjxt;
      case 'algeria':
      case '阿尔及利亚':
        return localizations.ik9qx39g7hpga2;
      case 'morocco':
      case '摩洛哥':
        return localizations.vctbndoe3q;
      case 'tunisia':
      case '突尼斯':
        return localizations.aofubktzol;
      case 'libya':
      case '利比亚':
        return localizations.lptvtrbhqh24m;
      case 'sudan':
      case '苏丹':
        return localizations.crrul9vhnhi8npjp;
      case 'ethiopia':
      case '埃塞俄比亚':
        return localizations.j3a2ikoecvc28;
      case 'kenya':
      case '肯尼亚':
        return localizations.xtdy7lecx9;
      case 'tanzania':
      case '坦桑尼亚':
        return localizations.peaaxvfrcy;
      case 'uganda':
      case '乌干达':
        return localizations.oui5zvzlqntq;
      case 'rwanda':
      case '卢旺达':
        return localizations.mbi51suykyokb3vyh;
      case 'nigeria':
      case '尼日利亚':
        return localizations.xf98h9maws;
      case 'ghana':
      case '加纳':
        return localizations.if8s8wtkhwibs9l5;
      case 'senegal':
      case '塞内加尔':
        return localizations.g4zjnl4jax;
      case 'ivory coast':
      case 'cote d\'ivoire':
      case '科特迪瓦':
        return localizations.hm4tz1zpz2v;
      case 'cameroon':
      case '喀麦隆':
        return localizations.p4kvyu8tbqcwr;
      case 'chile':
      case '智利':
        return localizations.enmcjxjf9cdeok04;
      case 'colombia':
      case '哥伦比亚':
        return localizations.dmfu1aqjbey0800km;
      case 'peru':
      case '秘鲁':
        return localizations.gw691hf4cln;
      case 'venezuela':
      case '委内瑞拉':
        return localizations.lrgrmetisi5;
      case 'ecuador':
      case '厄瓜多尔':
        return localizations.wn035v5c0jeokbtf;
      case 'bolivia':
      case '玻利维亚':
        return localizations.nayk0ya8m9ax7x;
      case 'paraguay':
      case '巴拉圭':
        return localizations.xyhace1nowxhc3;
      case 'uruguay':
      case '乌拉圭':
        return localizations.e0b11jk4inv01o24;
      case 'cuba':
      case '古巴':
        return localizations.kb6uuiyr7p;
      case 'jamaica':
      case '牙买加':
        return localizations.jqmyi7jbnylssl;
      case 'panama':
      case '巴拿马':
        return localizations.zk5fwpdj1iyk4n8n;
      case 'costa rica':
      case '哥斯达黎加':
        return localizations.q1p4duh59qkfgo08;
      case 'guatemala':
      case '危地马拉':
        return localizations.unmzcmlufjltej5rt;
      case 'honduras':
      case '洪都拉斯':
        return localizations.bbtx4xo7iwqq;
      case 'el salvador':
      case '萨尔瓦多':
        return localizations.ls1s6cyup4ghz;
      case 'nicaragua':
      case '尼加拉瓜':
        return localizations.lrf80my4bj7qc62;
      case 'dominican republic':
      case '多米尼加':
        return localizations.i3m8x643qe1ys;
      case 'haiti':
      case '海地':
        return localizations.g1kdwu7p7mzmrqf6;
      case 'puerto rico':
      case '波多黎各':
        return localizations.dm97ymq826hokfm;
      case 'trinidad and tobago':
      case '特立尼达和多巴哥':
        return localizations.ljvo9q5iwzaub1b;
      case 'bahamas':
      case '巴哈马':
        return localizations.os7dxv1iogm368b;
      case 'barbados':
      case '巴巴多斯':
        return localizations.mfk2p137f9lo2zzy;
      default:
        // F8dJ7jgN N
        return countryName;
    }
  }
}
